<a href="https://colab.research.google.com/github/djidachahrazed/nlp_machine_learning/blob/master/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

d1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
d2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
d3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

d1,d2,d3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
d1.shape,d1.ndim,d1.dtype,d1.size,type(d1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
d2.shape,d2.ndim,d2.dtype,d2.size,type(d2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
d3.shape,d3.ndim,d3.dtype,d3.size,type(d3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(d2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
a1=np.ones((10,2))
a1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
a2=np.zeros((7,2,3))
a2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
a4=np.arange(0,100,3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5=np.random.randint(0,10,size=(7,2))
a5

array([[1, 3],
       [1, 4],
       [1, 7],
       [4, 4],
       [1, 0],
       [3, 0],
       [4, 3]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6=np.random.random((3,5))
a6

array([[0.03391151, 0.81264013, 0.65812499, 0.69048401, 0.3256908 ],
       [0.41523973, 0.71097022, 0.71674594, 0.45936403, 0.73418075],
       [0.61530305, 0.22021872, 0.61683894, 0.94955353, 0.94194432]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

a7=np.random.randint(1,10,size=(3,7))
print(a7)
# Find the unique numbers in the array you just created
print(np.unique(a7))

[[7 1 1 9 9 4 9]
 [3 7 6 8 9 5 1]
 [3 8 6 8 9 4 1]]
[1 3 4 5 6 7 8 9]


In [25]:
# Find the 0'th index of the latest array you created
a7[0]


array([7, 1, 1, 9, 9, 4, 9])

In [26]:
# Get the first 2 rows of latest array you created
a7[:2]

array([[7, 1, 1, 9, 9, 4, 9],
       [3, 7, 6, 8, 9, 5, 1]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
a7[:2,:2]

array([[7, 1],
       [3, 7]])

In [28]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a8=np.random.randint(0,10,size=(3,5))
a9=np.ones((3,5))
a8,a9

(array([[0, 9, 3, 6, 1],
        [2, 0, 4, 0, 7],
        [0, 0, 1, 1, 5]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [29]:
# Add the two arrays together
a8+a9

array([[ 1., 10.,  4.,  7.,  2.],
       [ 3.,  1.,  5.,  1.,  8.],
       [ 1.,  1.,  2.,  2.,  6.]])

In [30]:
# Create another array of ones of shape (5, 3)
one=np.ones((5,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Try add the array of ones and the other most recent array together
a10=a8+a9+one.T

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [33]:
# Create another array of ones of shape (3, 5)
r1=np.ones((3,5))
r1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
# Subtract the new array of ones from the other most recent array
a10-r1

array([[ 1., 10.,  4.,  7.,  2.],
       [ 3.,  1.,  5.,  1.,  8.],
       [ 1.,  1.,  2.,  2.,  6.]])

In [38]:
# Multiply the ones array with the latest array
a11=a10*r1

In [44]:
# Take the latest array to the power of 2 using '**'
a11=a11**2
a11

array([[2.56000000e+02, 2.14358881e+08, 3.90625000e+05, 1.67772160e+07,
        6.56100000e+03],
       [6.55360000e+04, 2.56000000e+02, 1.67961600e+06, 2.56000000e+02,
        4.30467210e+07],
       [2.56000000e+02, 2.56000000e+02, 6.56100000e+03, 6.56100000e+03,
        5.76480100e+06]])

In [40]:
# Do the same thing with np.square()
np.square(a11)

array([[   16., 14641.,   625.,  4096.,    81.],
       [  256.,    16.,  1296.,    16.,  6561.],
       [   16.,    16.,    81.,    81.,  2401.]])

In [41]:
# Find the mean of the latest array using np.mean()
np.mean(a11)

29.266666666666666

In [46]:
# Find the maximum of the latest array using np.max()
np.max(a11)

214358881.0

In [47]:
# Find the minimum of the latest array using np.min()
np.min(a11)

256.0

In [48]:
# Find the standard deviation of the latest array
np.std(a11)

53425905.986692816

In [49]:
# Find the variance of the latest array
np.var(a11)

2854327430498939.5

In [51]:
# Reshape the latest array to (3, 5, 1)
a8.reshape(3,5,1)

array([[[0],
        [9],
        [3],
        [6],
        [1]],

       [[2],
        [0],
        [4],
        [0],
        [7]],

       [[0],
        [0],
        [1],
        [1],
        [5]]])

In [52]:
# Transpose the latest array
a8.T

array([[0, 2, 0],
       [9, 0, 0],
       [3, 4, 1],
       [6, 0, 1],
       [1, 7, 5]])

What does the transpose do?

In [54]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ray1=np.random.randint(0,10,size=(3,3))
ray2=np.random.randint(0,10,size=(3,2))
ray1,ray2

(array([[6, 4, 0],
        [0, 2, 1],
        [4, 9, 5]]),
 array([[6, 3],
        [6, 7],
        [0, 5]]))

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(ray1,ray2)

array([[ 60,  46],
       [ 12,  19],
       [ 78, 100]])

In [58]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ray3=np.random.randint(0,10,size=(4,3))
ray4=np.random.randint(0,10,size=(4,3))
ray3,ray4

(array([[7, 0, 8],
        [8, 1, 6],
        [9, 2, 6],
        [9, 8, 3]]),
 array([[0, 1, 0],
        [4, 4, 6],
        [8, 8, 2],
        [2, 2, 3]]))

In [62]:
# Perform a dot product on the two newest arrays you created
#np.dot(ray3,ray4)

It doesn't work. How would you fix it?

In [63]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(ray3.T,ray4)

array([[122, 129,  93],
       [ 36,  36,  34],
       [ 78,  86,  57]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [64]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ray5=np.random.randint(0,10,size=(4,4))
ray6=np.random.randint(0,10,size=(4,4))
ray5,ray6

(array([[7, 5, 7, 0],
        [7, 3, 0, 7],
        [3, 5, 7, 3],
        [2, 8, 2, 8]]),
 array([[1, 1, 1, 5],
        [2, 8, 3, 0],
        [3, 0, 4, 3],
        [7, 7, 6, 2]]))

In [65]:
# Compare the two arrays with '>'
ray5>ray6

array([[ True,  True,  True, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True]])

What happens when you compare the arrays with `>`?

In [66]:
# Compare the two arrays with '>='
ray5>=ray6

array([[ True,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True]])

In [67]:
# Find which elements of the first array are greater than 7
ray5>7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True]])

In [68]:
# Which parts of each array are equal? (try using '==')
ray5==ray6

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False, False, False, False]])

In [71]:
# Sort one of the arrays you just created in ascending order
ray5.sort()
ray5

array([[0, 5, 7, 7],
       [0, 3, 7, 7],
       [3, 3, 5, 7],
       [2, 2, 8, 8]])

In [74]:
# Sort the indexes of one of the arrays you just created
np.argsort(ray5)
ray5

array([[0, 5, 7, 7],
       [0, 3, 7, 7],
       [3, 3, 5, 7],
       [2, 2, 8, 8]])

In [76]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ray5)

14

In [77]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ray5)

0

In [81]:
ray5

array([[0, 5, 7, 7],
       [0, 3, 7, 7],
       [3, 3, 5, 7],
       [2, 2, 8, 8]])

In [82]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ray5,axis=1)

array([2, 2, 3, 2])

In [80]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ray5,axis=0)

array([0, 3, 2, 0])

In [83]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 0.82206016,  1.89679298, -0.24538812, -0.75373616, -0.88951443],
       [-0.81581028, -0.07710171,  0.34115197,  0.2766908 ,  0.82718325],
       [ 0.01300189,  1.45353408, -0.26465683,  2.72016917,  0.62566735]])

In [86]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.